name: bicep-StephenLab

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: 'StephenLab'
    LOCATION: 'southcentralus'
    AVD_SECURITY_GROUP: 'AVD Users - Host Pool'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Github Code Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

  gather-azure-data:
    runs-on: ubuntu-latest
    steps:
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlinescript: |
          $AVD_SECURITY_GROUP_ID = $( Get-AzADGroup -DisplayName $AVD_SECURITY_GROUP ).Id
          echo $( "AVD_SECURITY_GROUP_ID = $AVD_SECURITY_GROUP_ID" ) | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        azPSVersion: "latest"

    - name: Deploy main bicep file
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: 
                   location=${{ env.LOCATION }}
                   avdSecurityGroupId=${{ env.AVD_SECURITY_GROUP_ID }}