name: bicep-StephenLab

on:
  workflow_dispatch:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: 'StephenLab'
    LOCATION: 'southcentralus'
    AVD_SECURITY_GROUP: 'AVD Users - Host Pool'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Github Code Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Azure Script
      uses: azure/powershell@v1
      with:
        id: run-azure-script
        inlineScript: |
          $GroupObjectId = $( Get-AzADGroup -DisplayName '${{ env.AVD_SECURITY_GROUP }}' ).Id
          echo "ID=$GroupObjectId" >> $env:GITHUB_OUTPUT
        azPSVersion: latest
        
    - name: Deploy main bicep file
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: 
                   location=${{ env.LOCATION }}
                   avdSecurityGroupId=${{ steps.run-azure-script.outputs.ID }}