name: bicep-StephenLab

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: 'StephenLab'
    LOCATION: 'southcentralus'
    UAMI_NAME: 'UAMIScripts'
    # AVD_SECURITY_GROUP: 'AVD Users - Multi Session'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: 
                   location=${{ env.LOCATION }}
                   uamiName=${{ env.UAMI_NAME }}
