name: bicep-StephenLab

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: 'StephenLab'
    LOCATION: 'southcentralus'
    AVD_SECURITY_GROUP: 'AVD Users - Host Pool'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repository to Linux runner....
    - uses: actions/checkout@v2
    - name: Logging Linux runner into Azure....
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Deploying your main.bicep template.
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: 
                   location=${{ env.LOCATION }}